if (size(`ls -sl`))
{
    string $usdObj[] = `ls -sl`;
    string $usdObjName = $usdObj[0];
    string $usdFolderPath = "D:/GuruStudio/USD/";
    $usdObjName = ($usdFolderPath + $usdObjName);
    mayaUSDExport -sl -f $usdObjName;
}
else{
    window -t "USD Export Warning!" -width 400;
        columnLayout -adjustableColumn true;
            text -bgc 1 0 0 -label "Please select an object in the Outliner." -align "center";
        print "no";
    showWindow;
}